apiVersion: v1
kind: Namespace
metadata:
  name: app1
  labels:
    app.kubernetes.io/managed-by: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: app2
  labels:
    app.kubernetes.io/managed-by: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: app3
  labels:
    app.kubernetes.io/managed-by: argocd
