apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-of-apps
  namespace: argocd-a
spec:
  generators:
    - list:
        elements:
          - name: app1
            path: apps/app1
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/aali309/argocd-test-nested.git'
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: 'https://fake-cluster.argocd-b.svc'
        namespace: argocd-b    # ✅ This is key
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
