apiVersion: v1
kind: ConfigMap
metadata:
  name: config-service-config
  labels:
    app: config-service
    app.kubernetes.io/name: config-service
    app.kubernetes.io/part-of: parent-child-testing
data:
  app.properties: |
    # Application Configuration
    app.name=config-service
    app.version=1.0.0
    app.environment=development

    # Database Configuration
    db.host=localhost
    db.port=5432
    db.name=configdb
    db.pool.size=10

    # Logging Configuration
    log.level=INFO
    log.file=/var/log/app.log
    log.max.size=100MB
    log.max.files=5

    # Feature Flags
    feature.new-ui.enabled=true
    feature.analytics.enabled=false
    feature.debug.enabled=true

  nginx.conf: |
    user nginx;
    worker_processes auto;
    error_log /var/log/nginx/error.log warn;
    pid /var/run/nginx.pid;

    events {
        worker_connections 1024;
    }

    http {
        include /etc/nginx/mime.types;
        default_type application/octet-stream;
        
        log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                       '$status $body_bytes_sent "$http_referer" '
                       '"$http_user_agent" "$http_x_forwarded_for"';
        
        access_log /var/log/nginx/access.log main;
        
        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 2048;
        
        server {
            listen 80;
            server_name localhost;
            
            location / {
                root /usr/share/nginx/html;
                index index.html index.htm;
            }
            
            error_page 500 502 503 504 /50x.html;
            location = /50x.html {
                root /usr/share/nginx/html;
            }
        }
    }
