apiVersion: v1
kind: Secret
metadata:
  name: config-service-secrets
  labels:
    app: config-service
    app.kubernetes.io/name: config-service
    app.kubernetes.io/part-of: parent-child-testing
type: Opaque
stringData:
  admin-password: "super-secure-admin-password"
  encryption-key: "config-service-encryption-key-256bit"
  database-password: "config-db-password-secure"
  api-token: "config-service-api-token-xyz789"
