apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test-nested-values
spec:
  goTemplate: true
  goTemplateOptions: [ "missingkey=error" ]
  generators:
  - matrix:
      generators:
      - clusters:
          selector:
            matchLabels:
              enabled: "true"
          values:
            cluster: '{{ index .metadata.labels "app.kubernetes.io/name" }}'
            environment: '{{ index .metadata.labels "environment"}}'
      - git:
          repoURL: 'https://github.com/aali309/argocd-test-nested.git'
          revision: HEAD
          files:
          - path: 'apps/*/argo-config.json'
  template:
    metadata:
      name: "{{.nameNormalized}}-{{.app}}"
    spec:
      project: default
      sources:
      # by default all values are within the values directory
      - repoURL: 'https://github.com/aali309/argocd-test-nested.git'
        targetRevision: HEAD
        ref: helmValues
      # template the helm charts using the given values
      - repoURL: '{{ .helmRepo }}'
        chart: '{{ .helmChart }}'
        targetRevision: '{{ dig "overrides" .values.environment "helmChartVersion" .helmChartVersion . }}'
        helm:
          valueFiles:
          - '$helmValues/apps/{{.app}}/values/globals.yaml'
          - '$helmValues/apps/{{.app}}/values/environments/{{.values.environment}}.yaml'
          - '$helmValues/apps/{{.app}}/values/clusters/{{.values.cluster}}.yaml'
          ignoreMissingValueFiles: true
      destination:
        server: '{{.server}}'
        namespace: test-namespace
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
