# File: deploy-secondary-argocd.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deploy-secondary-argocd
  namespace: argocd-e2e # Primary Argo CD's namespace
spec:
  project: default
  source:
    repoURL: https://github.com/aali309/argocd-test-nested.git # Your repo
    targetRevision: main
    path: apps/secondary-argocd # Correct path to manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: namespace-b # Target namespace for secondary Argo CD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
