apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-e2e-controller-reader
rules:
# Core resources - comprehensive list
- apiGroups: [ "" ]
  resources: [ "*" ]
  verbs: [ "get", "list", "watch" ]
# Apps resources
- apiGroups: [ "apps" ]
  resources: [ "*" ]
  verbs: [ "get", "list", "watch" ]
# RBAC resources
- apiGroups: [ "rbac.authorization.k8s.io" ]
  resources: [ "*" ]
  verbs: [ "get", "list", "watch" ]
# Extensions resources
- apiGroups: [ "extensions" ]
  resources: [ "*" ]
  verbs: [ "get", "list", "watch" ]
# Networking resources
- apiGroups: [ "networking.k8s.io" ]
  resources: [ "*" ]
  verbs: [ "get", "list", "watch" ]
# Storage resources
- apiGroups: [ "storage.k8s.io" ]
  resources: [ "*" ]
  verbs: [ "get", "list", "watch" ]
# Batch resources
- apiGroups: [ "batch" ]
  resources: [ "*" ]
  verbs: [ "get", "list", "watch" ]
# Autoscaling resources
- apiGroups: [ "autoscaling" ]
  resources: [ "*" ]
  verbs: [ "get", "list", "watch" ]
# Policy resources
- apiGroups: [ "policy" ]
  resources: [ "*" ]
  verbs: [ "get", "list", "watch" ]
# Scheduling resources
- apiGroups: [ "scheduling.k8s.io" ]
  resources: [ "*" ]
  verbs: [ "get", "list", "watch" ]
# Additional common API groups
- apiGroups: [ "admissionregistration.k8s.io" ]
  resources: [ "*" ]
  verbs: [ "get", "list", "watch" ]
- apiGroups: [ "apiextensions.k8s.io" ]
  resources: [ "*" ]
  verbs: [ "get", "list", "watch" ]
- apiGroups: [ "apiregistration.k8s.io" ]
  resources: [ "*" ]
  verbs: [ "get", "list", "watch" ]
- apiGroups: [ "coordination.k8s.io" ]
  resources: [ "*" ]
  verbs: [ "get", "list", "watch" ]
- apiGroups: [ "discovery.k8s.io" ]
  resources: [ "*" ]
  verbs: [ "get", "list", "watch" ]
- apiGroups: [ "flowcontrol.apiserver.k8s.io" ]
  resources: [ "*" ]
  verbs: [ "get", "list", "watch" ]
- apiGroups: [ "metrics.k8s.io" ]
  resources: [ "*" ]
  verbs: [ "get", "list", "watch" ]
- apiGroups: [ "node.k8s.io" ]
  resources: [ "*" ]
  verbs: [ "get", "list", "watch" ]
- apiGroups: [ "scheduling.k8s.io" ]
  resources: [ "*" ]
  verbs: [ "get", "list", "watch" ]
# OpenShift Cluster Management resources
- apiGroups: [ "cluster.open-cluster-management.io" ]
  resources: [ "*" ]
  verbs: [ "get", "list", "watch" ]
# OpenShift specific resources
- apiGroups: [ "operator.openshift.io" ]
  resources: [ "*" ]
  verbs: [ "get", "list", "watch" ]
- apiGroups: [ "config.openshift.io" ]
  resources: [ "*" ]
  verbs: [ "get", "list", "watch" ]
- apiGroups: [ "console.openshift.io" ]
  resources: [ "*" ]
  verbs: [ "get", "list", "watch" ]
# ArgoCD specific resources
- apiGroups: [ "argoproj.io" ]
  resources: [ "*" ]
  verbs: [ "get", "list", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-e2e-controller-reader-binding
subjects:
- kind: ServiceAccount
  name: argocd-application-controller
  namespace: argocd-e2e
roleRef:
  kind: ClusterRole
  name: argocd-e2e-controller-reader
  apiGroup: rbac.authorization.k8s.io
