apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  namespace: app4
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: my-app
  replicas: 1
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: nginx:1.14.2
