apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-statefulset
  namespace: argocd
spec:
  selector:
    matchLabels:
      app: my-app
  serviceName: "my-service"
  replicas: 1
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: nginx:1.14.2
        ports:
        - containerPort: 80
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
