apiVersion: v1
kind: Service
metadata:
  name: blue-green-active
  namespace: rollout-test
  labels:
    app: blue-green-app
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: blue-green-app

