apiVersion: v1
kind: Service
metadata:
  name: stable-service
  namespace: rollout-test
  labels:
    app: canary-app
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: canary-app

