apiVersion: v1
kind: Service
metadata:
  name: simple-service
  namespace: rollout-test
  labels:
    app: simple-app
spec:
  ports:
  - port: 8080
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: simple-app

