apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: simple-rollout
  namespace: rollout-test
  labels:
    app: simple-app
spec:
  replicas: 3
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: simple-app
  template:
    metadata:
      labels:
        app: simple-app
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
  strategy:
    blueGreen:
      activeService: simple-service
      autoPromotionEnabled: true
      # Auto-promote immediately to ensure pods are created and running

