apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: simple-rollout
  namespace: rollout-test
  labels:
    app: simple-app
spec:
  replicas: 3
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: simple-app
  template:
    metadata:
      labels:
        app: simple-app
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000820000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: nginx
        image: nginxinc/nginx-unprivileged:1.21
        ports:
        - containerPort: 8080
          name: http
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          runAsUser: 1000820000
          seccompProfile:
            type: RuntimeDefault
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
  strategy:
    blueGreen:
      activeService: simple-service
      autoPromotionEnabled: true
      # Auto-promote immediately to ensure pods are created and running

