apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: custom-project-no-apps
  namespace: appproject-test
  labels:
    app.kubernetes.io/name: custom-project-no-apps
    app.kubernetes.io/part-of: gitops-console-plugin-test
    project-type: custom
spec:
  description: "Custom project without any associated applications - tests 'No Applications' display"
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'

