apiVersion: apps/v1
kind: Deployment
metadata:
  name: app4-deployment
  namespace: app4
  labels:
    app: app4
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app4
  template:
    metadata:
      labels:
        app: app4
    spec:
      containers:
      - name: app4
        image: nginx:1.21
        ports:
        - containerPort: 80
        env:
        - name: APP_NAME
          valueFrom:
            configMapKeyRef:
              name: app4-config
              key: app-name
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: app4-config
              key: environment
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
      volumes:
      - name: config-volume
        configMap:
          name: app4-config
