apiVersion: apps/v1
kind: Deployment
metadata:
  name: app3-deployment
  namespace: app3
  labels:
    app: app3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app3
  template:
    metadata:
      labels:
        app: app3
    spec:
      containers:
      - name: app3
        image: nginx:1.21
        ports:
        - containerPort: 80
        env:
        - name: APP_NAME
          valueFrom:
            configMapKeyRef:
              name: app3-config
              key: app-name
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: app3-config
              key: environment
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
      volumes:
      - name: config-volume
        configMap:
          name: app3-config
