apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app-2-deployment
  namespace: gitops-test-ns-2
  labels:
    app: test-app-2
    environment: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-app-2
  template:
    metadata:
      labels:
        app: test-app-2
        environment: staging
    spec:
      containers:
      - name: test-app-2
        image: nginxinc/nginx-unprivileged:1.25
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: test-app-2-service
  namespace: gitops-test-ns-2
  labels:
    app: test-app-2
spec:
  selector:
    app: test-app-2
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
