apiVersion: v1
kind: ConfigMap
metadata:
  name: api-service-config
  labels:
    app: api-service
    app.kubernetes.io/name: api-service
    app.kubernetes.io/part-of: parent-child-testing
data:
  config.yaml: |
    server:
      port: 3000
      host: 0.0.0.0
    
    database:
      host: postgres
      port: 5432
      name: apidb
      pool:
        min: 2
        max: 10
    
    redis:
      host: redis
      port: 6379
      db: 0
      ttl: 3600
    
    logging:
      level: info
      format: json
      output: stdout
    
    features:
      rate_limiting: true
      caching: true
      metrics: true
      tracing: true
  
  api-schema.json: |
    {
      "openapi": "3.0.0",
      "info": {
        "title": "API Service",
        "version": "1.0.0",
        "description": "Main API service for the application"
      },
      "paths": {
        "/health": {
          "get": {
            "summary": "Health check endpoint",
            "responses": {
              "200": {
                "description": "Service is healthy"
              }
            }
          }
        },
        "/api/v1/users": {
          "get": {
            "summary": "Get all users",
            "responses": {
              "200": {
                "description": "List of users"
              }
            }
          }
        }
      }
    }
