apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-service-monitor
  labels:
    app: api-service
    app.kubernetes.io/name: api-service
    app.kubernetes.io/part-of: parent-child-testing
spec:
  selector:
    matchLabels:
      app: api-service
  endpoints:
  - port: http
    interval: 30s
    path: /metrics
    scheme: http
