apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: api-service
    app.kubernetes.io/name: api-service
    app.kubernetes.io/part-of: parent-child-testing
spec:
  clusterIP: None
  selector:
    app: api-service
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    name: http
