# App-of-Apps managed by the secondary Argo CD instance
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: namespace-b
  annotations:
    argocd.argoproj.io/managed-by-url: "https://argocd-instance-b.example.com"
spec:
  project: default
  source:
    repoURL: https://github.com/aali309/argocd-test-nested.git
    targetRevision: main
    path: apps/app-of-apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-e2e
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
