apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: namespace-b
  annotations:
    argocd.argoproj.io/managed-by-url: "https://localhost:8082"
spec:
  project: default
  source:
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
    path: guestbook
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
