# Sample application managed by the secondary Argo CD instance
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: namespace-b
spec:
  project: default
  source:
    repoURL: https://github.com/aali309/argocd-test-nested.git  # Replace with your repo URL
    targetRevision: main
    path: apps/app1  # Path to your app's manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: default