apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-server-cross-namespace-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-application-controller # or custom role if needed
subjects:
- kind: ServiceAccount
  name: argocd-server
  namespace: namespace-a
